name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    # Build and push the server image (depends on the base image)
    - name: Build and push server image
      run: |
        SERVER_IMAGE="ghcr.io/${{ github.repository }}/terminal-server"
        SERVER_TAG="latest"
        cd src/
        docker build . -f Dockerfile -t $SERVER_IMAGE:$SERVER_TAG
        docker push $SERVER_IMAGE:$SERVER_TAG

    # Build and push all course images
    - name: Build and push course images
      run: |
        for dir in courses/*/; do
          if [ -f "$dir/Dockerfile" ]; then
            COURSE_NAME=$(basename "$dir")
            IMAGE="ghcr.io/${{ github.repository }}/terminal-${COURSE_NAME}"
            docker build "$dir" -t "$IMAGE:latest"
            docker push "$IMAGE:latest"
          fi
        done
