services:
  linux-1:
    build:
      context: ./linux-1
    image: ghcr.io/jonasbg/linux-webterminal/terminal-linux-1:latest

  linux-2:
    build:
      context: ./linux-2
    image: ghcr.io/jonasbg/linux-webterminal/terminal-linux-2:latest

  linux-3:
    build:
      context: ./linux-3
    image: ghcr.io/jonasbg/linux-webterminal/terminal-linux-3:latest

  docker:
    build:
      context: ./docker
    image: ghcr.io/jonasbg/linux-webterminal/terminal-docker:latest
